# Generated by Django 5.2.17 on 2026-09-09 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Apex Gym & Fitness Center', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logo/')),
                ('address', models.TextField(default='123 Fitness Avenue, Tech District, City Center')),
                ('phone', models.CharField(default='+1 (555) 019-2834', max_length=20)),
                ('email', models.EmailField(default='contact@apexgym.com', max_length=254)),
                ('opening_time', models.TimeField(default=datetime.time(6, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
